---
driver:
  name: docker
  hostname: rabbitmq.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: rabbitmq
  grains:
    noservices: False
  state_top:
    base:
      "*":
        - rabbitmq
  pillars:
    top.sls:
      base:
        "*":
          - rabbitmq

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: rabbitmq_server
    provisioner:
      pillars-from-files:
        rabbitmq.sls: tests/pillar/rabbitmq_server.sls

  - name: rabbitmq_ssl_server
    provisioner:
      pillars-from-files:
        rabbitmq.sls: tests/pillar/rabbitmq_ssl_server.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
